### ISSUE TITLE
[Question] this repo vs. govau/dta-uikit-base

### ISSUE THREAD

**Issue by svict4** [govCMS/uikit-bootstrap#2]
What is the difference between this repo and the [UIKit Drupal 8 theme provided by DTA](https://github.com/govau/dta-uikit-base)?
I'm guessing this just Bootstrap themed to look like the UIKit, while the other repo more aligns to the actual component structure?

**Comment by alex-page** [comment]
This repository hasn't been updated in a while. From memory the developers at GovCMS were familiar working in the bootstrap theme. So instead of starting from scratch they modified the bootstrap theme to look like the uikit.

There is ongoing work on a [new theme for govCMS](https://github.com/govCMS/govcms8_uikit_starter) this is being worked on by govCMS and we hope to collaborate together more in the future when our templates are completed.

The DTA uikit-base is a repository created for the new beta.dta.gov.au however it is outdated and needs to be updated with our new components and changes.

**Comment by pandaskii** [comment]
This repo was developed as a bootstrap stylesheet based on the DTA's UI-Kit so that the Drupal theme developer can keep using bootstrap.

As @alex-page mentioned, it cannot keep up a pace with the evolvement of the latest DTA style guide.

This repo will be deprecated. A GovCMS8 base theme has been developed here https://github.com/govCMS/govcms8_uikit_starter and there is no GovCMS7 version available.

**Comment by svict4** [comment]
Ah okay that's a bit clearer, thanks folks.

I was in the process of starting a new composer built project from the [GovCMS8-project repo](https://github.com/govCMS/govCMS8-project).
The instructions on [GovCMS8 core ](https://github.com/govCMS/govcms8) list _this repo_ and the [govCMS8-UI](https://github.com/govCMS/govCMS8-ui).

Am I now right in saying that both of those UI repos should be dropped in favour of [govcms8_the uikit_starter](https://github.com/govCMS/govcms8_uikit_starter). If so, would I run and build the composer project, then dump the uikit_starter repo on top?

**Comment by alex-page** [comment]
I would say so, the govcms8-UI is currently the most up to date Drupal 8 theme using the Design System.

**Comment by pandaskii** [comment]
@svict4 GovCMS8-project repo is getting some issues now since the compatible issues of third-party libraries with drupal.org's policy. I am working on a fix now and will do a release tomorrow or Thursday.

If your project is urgent, please read https://github.com/govCMS/govCMS8/blob/1.x/composer.json and pay special attention to custom repositories section

**Comment by alex-page** [comment]
@svict4 if you are happy with responses feel free to close the issue 👍
